#!/bin/sh

cleanup() {
    echo "\n----- SERVER STOPPED -----\nCleaning up..."
    rm server
    echo "Done"
}

export BASE_URL="https://s3-us-west-2.amazonaws.com/lolth.demo"
export PORT=8728
go build -o server
chmod +x server
trap 'cleanup' INT
./server
