#!/bin/sh

cleanup() {
    echo "\n----- SERVER STOPPED -----\nCleaning up..."
    rm server
    echo "Done"
}

export BASE_URL="https://s3-us-west-1.amazonaws.com/quali-landing"
export PORT=8728
go build -o server
chmod +x server
trap 'cleanup' INT
./server
